steps:
  - name: 'eclipse-temurin:17-jdk-alpine'
    entrypoint: './gradlew'
    args: ['bootJar', '--no-daemon']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/dk-vision', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/dk-vision']
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dk-vision'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/dk-vision'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=prod'
substitutions:
  _REGION: us-central1
options:
  logging: CLOUD_LOGGING_ONLY
